---
services:
  # main services
  zookeeper:
    image: bitnami/zookeeper:3.8 # \d+\.\d+
  kafka:
    image: bitnami/kafka:3.7 # \d+\.\d+
  redis:
    image: bitnami/valkey:7.2 # \d+\.\d+
  clickhouse:
    image: clickhouse/clickhouse-server:24.3 # \d+\.[38]
  traefik:
    image: traefik:v3.0 # v\d+\.\d+
  maxmind-geoipupdate:
    image: ghcr.io/maxmind/geoipupdate:v7
  ipinfo-geoipupdate:
    image: ghcr.io/akvorado/ipinfo-geoipupdate:latest
    build:
      context: .
      dockerfile: Dockerfile.ipinfo-geoipupdate
  akvorado:
    image: ghcr.io/akvorado/akvorado:1.11.1

  # observability
  grafana:
    image: grafana/grafana-oss:10.2.6 # \d+\.\d+\.\d+
  prometheus:
    image: prom/prometheus:v2.47.2 # v\d+\.\d+\.\d+
  node-exporter:
    image: prom/node-exporter:v1.7.0 # v\d+\.\d+\.\d+
  kafka-jmx-exporter:
    image: bitnami/jmx-exporter:0
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2 # v\d+\.\d+\.\d+

  # for tests
  srlinux:
    image: ghcr.io/nokia/srlinux:23.7.1
  postgres:
    image: bitnami/postgresql:16.3.0 # \d+\.\d+\.0
  mysql:
    image: bitnami/mariadb:11.3 # \d+\.\d+

    image: bitnami/zookeeper:3.8
    image: bitnami/kafka:3.7
    image: bitnami/valkey:7.2
    image: clickhouse/clickhouse-server:24.3
    image: traefik:v3.0
    image: ghcr.io/maxmind/geoipupdate:v7
    image: ghcr.io/akvorado/ipinfo-geoipupdate:latest
    image: ghcr.io/akvorado/akvorado:1.11.1
    image: grafana/grafana-oss:10.2.
    image: prom/prometheus:v2.47.2
    image: prom/node-exporter:v1.7.0
    image: bitnami/jmx-exporter:0
    image: provectuslabs/kafka-ui:v0.7.2
    image: ghcr.io/nokia/srlinux:23.7.1
    image: bitnami/postgresql:16.3.0
    image: bitnami/mariadb:11.3
